"""Cluster-label persistence for the paper map / author network.

The label payload itself is generated by TF-IDF top-terms
(``alma.ai.clustering.label_clusters_tfidf``) — the LLM-backed path
was removed in 2026-04 (see ``tasks/01_LLM_PRODUCTION_EXIT.md``). This
module owns three concerns:

* ``compute_cluster_signature`` — stable hash of a cluster's member set,
  so the cache invalidates itself whenever the membership changes and
  stays valid otherwise.
* ``fetch_cached_labels`` — read cached label rows for a batch of
  signatures (used by the GET path so the rendered graph can reuse
  labels written by an earlier refresh).
* ``store_label`` — upsert one label row.

The endpoint that triggers a refresh lives in
``alma.api.routes.graphs._cluster_label_refresh_impl`` and writes
``model = 'tfidf'`` for every cluster.
"""

from __future__ import annotations

import hashlib
import json
import logging
import sqlite3
from datetime import datetime
from typing import Iterable

logger = logging.getLogger(__name__)


def compute_cluster_signature(member_ids: Iterable[str]) -> str:
    """Stable hash of a cluster's member set, independent of ordering."""
    serialised = "\n".join(sorted(str(m) for m in member_ids if m))
    return hashlib.sha1(serialised.encode("utf-8")).hexdigest()


def fetch_cached_labels(
    conn: sqlite3.Connection,
    *,
    graph_type: str,
    scope: str,
    signatures: Iterable[str],
) -> dict[str, dict[str, object]]:
    """Read cached label rows for a batch of cluster signatures."""
    sig_list = [s for s in signatures if s]
    if not sig_list:
        return {}
    placeholders = ",".join("?" * len(sig_list))
    try:
        rows = conn.execute(
            f"""
            SELECT cluster_signature, label, description, top_terms, model, updated_at
            FROM graph_cluster_labels
            WHERE graph_type = ? AND scope = ?
              AND cluster_signature IN ({placeholders})
            """,
            [graph_type, scope, *sig_list],
        ).fetchall()
    except sqlite3.OperationalError:
        return {}

    out: dict[str, dict[str, object]] = {}
    for row in rows:
        if isinstance(row, sqlite3.Row):
            sig = row["cluster_signature"]
            entry = {
                "label": str(row["label"] or ""),
                "description": str(row["description"] or ""),
                "top_terms": row["top_terms"] or "[]",
                "model": str(row["model"] or ""),
                "updated_at": str(row["updated_at"] or ""),
            }
        else:
            sig = row[0]
            entry = {
                "label": str(row[1] or ""),
                "description": str(row[2] or ""),
                "top_terms": row[3] or "[]",
                "model": str(row[4] or ""),
                "updated_at": str(row[5] or ""),
            }
        try:
            entry["top_terms_list"] = json.loads(str(entry["top_terms"] or "[]"))
        except Exception:
            entry["top_terms_list"] = []
        out[sig] = entry
    return out


def store_label(
    conn: sqlite3.Connection,
    *,
    graph_type: str,
    scope: str,
    signature: str,
    label: str,
    description: str,
    top_terms: list[str],
    model: str,
) -> None:
    """Persist a single cluster label row (upsert on PK)."""
    try:
        conn.execute(
            """
            INSERT INTO graph_cluster_labels
              (graph_type, scope, cluster_signature, label, description,
               top_terms, model, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(graph_type, scope, cluster_signature)
            DO UPDATE SET
                label = excluded.label,
                description = excluded.description,
                top_terms = excluded.top_terms,
                model = excluded.model,
                updated_at = excluded.updated_at
            """,
            (
                graph_type,
                scope,
                signature,
                label.strip()[:160] or f"Cluster {signature[:6]}",
                description.strip()[:600],
                json.dumps(top_terms[:12], ensure_ascii=False),
                model.strip()[:120],
                datetime.now().isoformat(),
            ),
        )
        if conn.in_transaction:
            conn.commit()
    except sqlite3.OperationalError as exc:
        logger.warning("Failed caching cluster label: %s", exc)
