/** Real Library: ordinary curation, optional detail fetches, keyboard/mobile and failures. */
import assert from 'node:assert/strict'
import { chromium } from 'playwright'
const base = process.env.ALMA_URL ?? 'http://127.0.0.1:5173'
const browser = await chromium.launch({ executablePath: process.env.ALMA_BROWSER_EXECUTABLE || undefined })
const errors = []
let restore
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  await page.addInitScript(() => localStorage.setItem('alma.tour.library.completed', 'done'))
  page.on('pageerror', e => errors.push(String(e)))
  const requests = []
  page.on('request', r => requests.push(r.url()))
  await page.goto(`${base}/#/library`)
  await page.getByPlaceholder('Search saved papers...').waitFor({ timeout: 30_000 })
  await page.getByRole('row').nth(1).waitFor()
  const imports = page.locator('summary', { hasText: 'Import details' })
  const metadata = page.locator('summary', { hasText: 'Review Library metadata' })
  assert.equal(requests.some(u => u.includes('/import/unresolved?limit=250')), false)
  assert.equal(requests.some(u => /\/api\/v1\/insights(?:\?|$)/.test(u)), false)
  assert.equal(await page.getByRole('button', { name: 'Resolve OpenAlex', exact: true }).isVisible(), false)
  assert.equal(await page.getByRole('tab', { name: 'Analytics', exact: true }).count(), 0)
  await page.getByRole('button', { name: 'Import Papers', exact: true }).click()
  await page.getByRole('dialog', { name: 'Import Papers', exact: true }).waitFor()
  await page.keyboard.press('Escape')
  await page.getByPlaceholder('Search saved papers...').fill('zz-no-such-library-paper-68')
  await page.getByText('No saved papers match your search', { exact: true }).waitFor()
  assert.equal(await page.getByText('No saved papers yet', { exact: true }).count(), 0)
  await page.getByPlaceholder('Search saved papers...').fill('')
  await page.getByRole('row').nth(1).waitFor()
  for (const width of [1440, 390]) {
    await page.setViewportSize({ width, height: 1000 })
    await page.getByRole('button', { name: 'Import Papers', exact: true }).scrollIntoViewIfNeeded()
    await page.screenshot({ path: `/tmp/alma-68-library-default-${width}.png` })
    await metadata.focus(); await page.keyboard.press('Enter')
    await metadata.evaluate(el => el.scrollIntoView({ block: 'start' }))
    await page.screenshot({ path: `/tmp/alma-68-library-expanded-${width}.png` })
    await metadata.click()
    await imports.focus(); await page.keyboard.press('Enter')
    await page.getByRole('button', { name: 'Resolve OpenAlex', exact: true }).waitFor()
    await imports.evaluate(el => el.scrollIntoView({ block: 'start' }))
    await page.screenshot({ path: `/tmp/alma-68-library-imports-${width}.png` })
    const bounds = await imports.boundingBox()
    assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= width + 1)
    await imports.click()
  }
  assert.ok(requests.some(u => u.includes('/import/unresolved?limit=250')))
  await page.setViewportSize({ width: 1440, height: 1000 })
  await page.locator('[title="Card view"]').click()
  const cardSelect = page.getByRole('combobox').nth(1)
  await cardSelect.waitFor()
  const previousLabel = await cardSelect.innerText()
  const oldStatus = { 'Not on reading list': null, Reading: 'reading', Done: 'done', Excluded: 'excluded' }[previousLabel]
  assert.notEqual(oldStatus, undefined)
  const changed = page.waitForResponse(r => r.url().endsWith('/reading-status') && r.request().method() === 'PATCH')
  await cardSelect.click()
  await page.getByRole('option', { name: oldStatus === 'reading' ? 'Done' : 'Reading', exact: true }).click()
  const response = await changed; assert.ok(response.ok())
  restore = { url: response.url(), status: oldStatus }
  assert.ok((await page.request.patch(restore.url, { data: { reading_status: restore.status } })).ok())
  restore = undefined
  await page.locator('[title="Compact table view"]').click()
  await page.getByRole('row').nth(1).getByRole('checkbox').click()
  assert.equal(await page.getByRole('button', { name: 'Clear Rating', exact: true }).isVisible(), false)
  await page.locator('summary', { hasText: 'Maintain selected papers' }).click()
  assert.equal(await page.getByRole('button', { name: 'Clear Rating', exact: true }).isEnabled(), true)
  await page.getByRole('button', { name: 'Remove', exact: true }).click()
  await page.getByRole('alertdialog').getByRole('button', { name: 'Cancel', exact: true }).click()
  await page.getByRole('button', { name: 'Clear selection', exact: true }).click()
  await page.getByRole('tab', { name: 'Collections', exact: true }).click()
  const admin = page.locator('summary', { hasText: 'Manage collection:' }).first()
  await admin.waitFor()
  assert.equal(await page.getByRole('button', { name: 'Edit collection', exact: true }).first().isVisible(), false)
  await admin.click()
  await page.getByRole('button', { name: 'Edit collection', exact: true }).first().click()
  await page.getByRole('dialog', { name: 'Edit Collection', exact: true }).waitFor()
  await page.keyboard.press('Escape')
  await page.getByRole('tab', { name: 'Tags', exact: true }).click()
  await page.locator('summary', { hasText: 'Tune tags' }).waitFor()
  assert.equal(requests.some(u => u.includes('merge-suggestions')), false)
  await page.locator('summary', { hasText: 'Tune tags' }).click()
  await page.getByRole('button', { name: 'AI Generate Suggestions', exact: true }).waitFor()
  await page.goto(`${base}/#/library?tab=analytics`)
  await page.getByRole('tab', { name: 'Overview', exact: true }).waitFor({ timeout: 30_000 })
  await page.route('**/api/v1/library/workflow-summary', route => route.fulfill({ status: 503, contentType: 'application/json', body: '{"detail":"unavailable"}' }))
  await page.goto(`${base}/#/library`); await page.reload()
  await page.getByText('Library summary is unavailable.', { exact: true }).waitFor({ timeout: 30_000 })
  assert.equal(await page.getByText('Every saved paper is cleanly identified.', { exact: true }).count(), 0)
  await page.unroute('**/api/v1/library/workflow-summary')
  await page.getByRole('button', { name: 'Retry', exact: true }).click()
  await page.getByText('Library summary is unavailable.', { exact: true }).waitFor({ state: 'hidden' })
  assert.deepEqual(errors, [])
  console.log('PASS Library: imports available without diagnostics, hidden queries gated, search truth, reversible reading, contextual bulk maintenance, collection edit, tag tuning, analytics deep link, outage/retry, keyboard/mobile.')
} finally {
  if (restore) {
    const context = await browser.newContext()
    await context.request.patch(restore.url, { data: { reading_status: restore.status } })
  }
  await browser.close()
}
